export const gameOverScreen = {
  gos_cow: {
    position: "absolute",
    right: "15%",
  },
  gos_maid: {
    position: "absolute",
    left: "16%",
  },
  gos_bigStar_center: {
    position: "absolute",
    resizeMode: "contain",
    top: "15%",
  },
  gos_littleStar_center: {
    position: "absolute",
    resizeMode: "contain",
    top: "12%",
  },
  gos_littleStar_right: {
    position: "absolute",
    resizeMode: "contain",
    top: "10%",
    right: "8%",
  },
  gos_littleStar_left: {
    position: "absolute",
    resizeMode: "contain",
    top: "10%",
    left: "8%",
  },
  gos_bigStar_right: {
    position: "absolute",
    resizeMode: "contain",
    top: "15%",
    right: "18%",
  },
  gos_bigStar_left: {
    position: "absolute",
    resizeMode: "contain",
    top: "15%",
    left: "8%",
  },
  gos_littleStar_middleL: {
    position: "absolute",
    resizeMode: "contain",
    top: "11%",
    left: "30%",
  },
  gos_bigStar_middleL: {
    position: "absolute",
    resizeMode: "contain",
    top: "5%",
    left: "25%",
  },
  gos_littleStar_middleR: {
    position: "absolute",
    resizeMode: "contain",
    top: "15%",
    right: "30%",
  },
  gos_bigStar_middleR: {
    position: "absolute",
    resizeMode: "contain",
    top: "7%",
    right: "25%",
  },
  gos_bigStar_middleL2: {
    position: "absolute",
    resizeMode: "contain",
    top: "18%",
    left: "30%",
  },
  gos_bottomRight_flower: {
    bottom: "3%",
    position: "absolute",
    height: "4%",
    resizeMode: "contain",
    right: "5%",
  },

  gos_middle_flower: {
    bottom: "32%",
    height: "3%",
    resizeMode: "contain",
    position: "absolute",
    left: "45%",
  },
  gos_bottomLeft_flower: {
    bottom: "6%",
    position: "absolute",
    height: "4%",
    resizeMode: "contain",
    left: "2%",
  },
  gos_topRight_flower: {
    bottom: "44%",
    height: "3%",
    resizeMode: "contain",
    position: "absolute",
    right: "1%",
  },
  gos_topLeft_flower: {
    bottom: "42%",
    height: "3%",
    resizeMode: "contain",
    position: "absolute",
    left: "10%",
  },
};
